//! Scenario-driven end-to-end tests. One `#[test]` per YAML file
//! under `scenarios/`, auto-generated by `dir-test`.
//!
//! Test naming convention: `<harness>::<path_with_underscores>`,
//! e.g. `scenarios/fix/file_create.yml` becomes
//! `scenario::scenarios::fix::file_create`.

use alint_testkit::{Scenario, assert_scenario, run_scenario};
use dir_test::{Fixture, dir_test};

#[dir_test(
    dir: "$CARGO_MANIFEST_DIR/scenarios",
    glob: "**/*.yml",
)]
#[allow(clippy::needless_pass_by_value)] // Required by dir-test's macro signature.
fn scenario(fixture: Fixture<&str>) {
    let path = fixture.path();
    let scenario = Scenario::from_yaml(fixture.content())
        .unwrap_or_else(|e| panic!("scenario at {path}: parse error: {e}"));
    let run = run_scenario(&scenario)
        .unwrap_or_else(|e| panic!("scenario {:?} at {path}: run error: {e}", scenario.name));
    assert_scenario(&scenario, &run).unwrap_or_else(|e| {
        panic!(
            "scenario {:?} at {path}: assertion failed: {e}",
            scenario.name
        )
    });
}
