//! `cross_file` — a value (or set of values, or the whole content,
//! or a set of paths) extracted from one authoritative `source`
//! file must hold a `relation:` to one or more `targets` (or the
//! filesystem). The unified cross-file value-relation kind
//! (architecture-synthesis primitive A): one kind, a `relation:`
//! knob, over the shared `crate::extract` + `normalize`. Design +
//! open questions: `docs/design/v0.12/cross_file.md`.
//!
//! `cross_file_value_equals` (v0.10) is a registered **alias** for
//! this kind with `relation` defaulting to `equals`; every existing
//! config is byte-compatible.
//!
//! `relation` groups into three shapes, validated in `build`:
//! - **value** (`equals` | `subset` | `superset` | `set_equals`):
//!   `source.extract` + `targets` (each with `extract`).
//! - **`identical`**: whole-file byte identity — `targets` with NO
//!   `extract`, no `source.extract` (optional `skip_header_lines`).
//! - **`resolves`**: each extracted source path must exist on disk —
//!   `source.extract`, NO `targets` (the forward half of
//!   `registry_paths_resolve`, which keeps its richer ergonomics).
//!
//! ```yaml
//! - id: workspace-versions-coherent
//!   kind: cross_file
//!   source:  { file: Cargo.toml, extract: { toml: "$.workspace.package.version" } }
//!   targets: { files: "crates/*/Cargo.toml", extract: { toml: "$.package.version" } }
//!   relation: equals               # equals (default) | subset | superset | set_equals
//!
//! # identical — the crate README must mirror the workspace README byte-for-byte.
//! - id: readme-mirrors-root
//!   kind: cross_file
//!   source:  { file: README.md }
//!   targets: { files: "crates/*/README.md" }
//!   relation: identical
//! ```

use std::path::PathBuf;

use alint_core::{
    Applicability, Context, Error, Extract, FixSpec, Fixer, Level, Result, Rule, RuleSpec, Scope,
    Violation,
};

use crate::fixers::{CreateAndRegisterFixer, CrossFileValueFixer, SyncFromFixer, ValueTargets};

mod eval;
mod spec;

use spec::{Options, Relation, Targets, resolve_targets, validate_extract_regexes, validate_shape};
// The options-schema fn is generated by `options_schema_for!(Options)` in `spec`;
// re-export it so the registry in `lib.rs` still finds `cross_file::options_schema`.
pub(crate) use spec::options_schema;
// Re-export the `normalize` model so the value fixer (`fixers::cross_file_ops`) can
// correlate its edits to the check's normalized comparison (audit: the fixer must
// skip a capture the check deemed correct under `normalize`).
pub(crate) use spec::{Normalize, apply_normalize};

#[derive(Debug)]
pub struct CrossFileRule {
    id: String,
    level: Level,
    policy_url: Option<String>,
    message: Option<String>,
    /// The source path (single-file mode) or the glob string (used
    /// for display in messages when `source_glob` is set).
    source_file: String,
    /// `Some` ⇒ glob-union source: `source_file` is the glob, and
    /// `source_values` unions the extracted values across every
    /// matching file. Set-relations only.
    source_glob: Option<Scope>,
    /// `Some` for value relations + `resolves`; `None` for `identical`.
    source_extract: Option<Extract>,
    /// `Some` for value relations + `identical`; `None` for `resolves`.
    targets: Option<Targets>,
    relation: Relation,
    /// Ordered transform list (empty = no normalization).
    normalize: Vec<Normalize>,
    allow_missing: bool,
    skip_header_lines: usize,
    /// `relation: registered` only: the `{path}`/`{dir}`/`{stem}` template that
    /// maps each matched member path to the value looked for (and, on fix, added)
    /// in the target list. `None` ⇒ the default `{path}` (the matched path).
    register_as: Option<String>,
    /// The `sync_from` fixer: on `relation: identical` a whole-file `SyncFromFixer`
    /// (mirror the source), on `relation: equals` a `CrossFileValueFixer`
    /// (propagate the source's extracted scalar into each target's node). `None`
    /// for every other relation and when no `fix:` block is set. Boxed so the two
    /// apply-based fixers share one field.
    fixer: Option<Box<dyn Fixer>>,
}

impl Rule for CrossFileRule {
    alint_core::rule_common_impl!();

    fn requires_full_index(&self) -> bool {
        // Cross-file: the source and every target may live
        // anywhere in the tree; never `--changed`-scoped.
        true
    }

    fn fixer(&self) -> Option<&dyn Fixer> {
        self.fixer.as_deref()
    }

    fn evaluate(&self, ctx: &Context<'_>) -> Result<Vec<Violation>> {
        Ok(self.evaluate_impl(ctx))
    }
}

/// Build the `sync_from` fixer for a `cross_file` rule, or reject an unsupported
/// `fix:` block. `sync_from` is the only fix op `cross_file` supports; its behavior
/// depends on the relation: on `identical` it is a WHOLE-FILE mirror
/// (`SyncFromFixer`), on `equals` it PROPAGATES the source's single extracted
/// scalar into each target's node (`CrossFileValueFixer`). A value relation with a
/// preserved header, or a set / resolves relation, has no single "correct" whole
/// value/bytes to write and is rejected.
#[allow(clippy::too_many_arguments)] // a config-parser dispatch: the shape inputs travel together
fn build_sync_from_fixer(
    fix: Option<&FixSpec>,
    relation: Relation,
    skip_header_lines: usize,
    source_file: &str,
    single_file_source: bool,
    source_extract: Option<&Extract>,
    targets: Option<&Targets>,
    normalize: &[Normalize],
    cfg: &impl Fn(String) -> Error,
) -> Result<Option<Box<dyn Fixer>>> {
    match fix {
        None => Ok(None),
        Some(FixSpec::SyncFrom { sync_from }) => {
            let tier = sync_from.applicability.unwrap_or(Applicability::Unsafe);
            match relation {
                Relation::Identical => {
                    if skip_header_lines != 0 {
                        return Err(cfg(
                            "`sync_from` cannot preserve the target's header: it copies the \
                             whole source file, which would overwrite the `skip_header_lines` \
                             header the rule deliberately ignores. Drop `skip_header_lines`, or \
                             fix the drift by hand."
                                .into(),
                        ));
                    }
                    // `identical` always has a single-file source (the glob-union
                    // form is rejected earlier for non-set relations); assert it.
                    debug_assert!(
                        single_file_source,
                        "identical must have a single-file source"
                    );
                    Ok(Some(Box::new(SyncFromFixer::new(
                        PathBuf::from(source_file),
                        tier,
                    ))))
                }
                Relation::Equals => {
                    // Value propagation: rewrite each target's extracted node to the
                    // source's single scalar. `validate_shape` guarantees a value
                    // relation has `source.extract` + `targets` with `extract`.
                    let source_extract = source_extract
                        .ok_or_else(
                            || cfg("`sync_from` on `equals` needs `source.extract`".into()),
                        )?
                        .clone();
                    let value_targets = build_value_targets(targets, cfg)?;
                    Ok(Some(Box::new(CrossFileValueFixer::new(
                        PathBuf::from(source_file),
                        source_extract,
                        value_targets,
                        normalize.to_vec(),
                        tier,
                    ))))
                }
                other => Err(cfg(format!(
                    "`sync_from` supports `relation: identical` (mirror the whole file) or \
                     `equals` (propagate one value); `{other:?}` is a set / resolves relation \
                     with no single value to propagate"
                ))),
            }
        }
        Some(FixSpec::CreateAndRegister {
            create_and_register,
        }) => {
            if relation != Relation::Registered {
                return Err(cfg(format!(
                    "`create_and_register` requires `relation: registered`; `{relation:?}` \
                     has no member list to register into"
                )));
            }
            let tier = create_and_register
                .applicability
                .unwrap_or(Applicability::Unsafe);
            let register_targets = build_register_targets(targets, cfg)?;
            Ok(Some(Box::new(CreateAndRegisterFixer::new(
                register_targets,
                tier,
            ))))
        }
        Some(other) => Err(cfg(format!(
            "fix.{} is not compatible with cross_file (only `sync_from` and `create_and_register`)",
            other.op_name()
        ))),
    }
}

/// Resolve the per-target ARRAY extract for `create_and_register`: each target
/// extract must be `Structured(fmt, "$.path[*]")` -- the same element query the
/// check uses -- with the trailing `[*]` stripped to the ARRAY path the fixer
/// appends into. A `lines` / `whole_file` / regex extract, or one that does not
/// select array elements with `[*]`, is rejected at load.
fn build_register_targets(
    targets: Option<&Targets>,
    cfg: &impl Fn(String) -> Error,
) -> Result<ValueTargets> {
    let array_extract = |ex: Option<&Extract>, what: &str| -> Result<Extract> {
        match ex {
            Some(Extract::Structured(fmt, query)) => {
                let array_query = query.strip_suffix("[*]").ok_or_else(|| {
                    cfg(format!(
                        "`relation: registered` {what} extract must select the array ELEMENTS \
                         with a trailing `[*]` (e.g. `$.workspace.members[*]`), so the check \
                         sees each element and the fix can locate the array; got `{query}`"
                    ))
                })?;
                Ok(Extract::Structured(*fmt, array_query.to_string()))
            }
            _ => Err(cfg(format!(
                "`relation: registered` {what} needs a STRUCTURED extract naming the list, \
                 e.g. `{{ toml: \"$.workspace.members[*]\" }}`"
            ))),
        }
    };
    match targets {
        Some(Targets::Glob { extract, .. }) => Ok(ValueTargets::Glob(array_extract(
            extract.as_ref(),
            "the `targets.files` glob",
        )?)),
        Some(Targets::List(list)) => {
            let mut out = Vec::with_capacity(list.len());
            for (file, ex) in list {
                let e = array_extract(ex.as_ref(), &format!("target `{file}`"))?;
                out.push((PathBuf::from(file), e));
            }
            Ok(ValueTargets::List(out))
        }
        None => Err(cfg("`relation: registered` needs `targets`".into())),
    }
}

/// Resolve the per-target extract for value propagation. A target `extract` must be
/// `Structured` (a `JSONPath` over a parsed format -- rewrite the located node) or
/// `Regex` (rewrite each capture group 1); a `lines` / `whole_file` extract has no
/// single scalar to set and is rejected at load.
fn build_value_targets(
    targets: Option<&Targets>,
    cfg: &impl Fn(String) -> Error,
) -> Result<ValueTargets> {
    let unsupported = |what: &str| {
        cfg(format!(
            "`sync_from` on `equals` needs a STRUCTURED (toml/json/yaml/xml/ini/hcl/dotenv/\
             properties JSONPath) or REGEX target extract; {what} has a lines/whole-file extract, \
             which has no single value to set."
        ))
    };
    // A propagation target's extract must be Structured or Regex.
    let value_extract = |ex: Option<&Extract>, what: &str| -> Result<Extract> {
        match ex {
            Some(e @ (Extract::Structured(..) | Extract::Regex(_))) => Ok(e.clone()),
            _ => Err(unsupported(what)),
        }
    };
    match targets {
        Some(Targets::Glob { extract, .. }) => Ok(ValueTargets::Glob(value_extract(
            extract.as_ref(),
            "the `targets.files` glob",
        )?)),
        Some(Targets::List(list)) => {
            let mut out = Vec::with_capacity(list.len());
            for (file, ex) in list {
                let e = value_extract(ex.as_ref(), &format!("target `{file}`"))?;
                out.push((PathBuf::from(file), e));
            }
            Ok(ValueTargets::List(out))
        }
        None => Err(cfg("`sync_from` on `equals` needs `targets`".into())),
    }
}

// A long but linear config parser: source (single / glob-union) x relation shape
// validation, then the `sync_from` fixer. Splitting it further would scatter the
// coupled shape checks; the fixer construction is already extracted.
#[allow(clippy::too_many_lines)]
pub fn build(spec: &RuleSpec) -> Result<Box<dyn Rule>> {
    alint_core::reject_scope_filter_on_cross_file(spec, "cross_file")?;
    let opts: Options = spec
        .deserialize_options()
        .map_err(|e| Error::rule_config(&spec.id, format!("invalid options: {e}")))?;
    let cfg = |msg: String| Error::rule_config(&spec.id, msg);

    let source_extract = match opts.source.extract {
        Some(spec) => Some(
            spec.resolve()
                .map_err(|e| cfg(format!("invalid `source.extract`: {e}")))?,
        ),
        None => None,
    };
    // Source: exactly one of `file` (single) or `files` (glob-union,
    // set relations only). For the glob form `source_file` holds the
    // glob string so violation messages still name a source.
    let (source_file, source_glob) = match (opts.source.file, opts.source.files) {
        (Some(f), None) => {
            if f.trim().is_empty() {
                return Err(cfg("`source.file` must not be empty".into()));
            }
            (f, None)
        }
        (None, Some(g)) => {
            if g.trim().is_empty() {
                return Err(cfg("`source.files` must not be empty".into()));
            }
            // `files` is a glob-union of extracted VALUES for the set relations, and
            // a glob of member PATHS for `registered` (each match is a member).
            if !matches!(
                opts.relation,
                Relation::Subset | Relation::Superset | Relation::SetEquals | Relation::Registered
            ) {
                return Err(cfg(format!(
                    "`source.files` (a glob) requires a set relation \
                     (subset / superset / set_equals) or `registered`, not `{:?}`",
                    opts.relation
                )));
            }
            let scope = Scope::from_patterns(std::slice::from_ref(&g))
                .map_err(|e| cfg(format!("invalid `source.files` glob: {e}")))?;
            (g, Some(scope))
        }
        (Some(_), Some(_)) => {
            return Err(cfg(
                "set exactly one of `source.file` (a path) or `source.files` (a glob), not both"
                    .into(),
            ));
        }
        (None, None) => {
            return Err(cfg(
                "`source` needs `file` (a path) or `files` (a glob-union over set relations)"
                    .into(),
            ));
        }
    };
    // Glob-union + `whole_file` would union whole-file CONTENTS as set
    // members — semantically odd and never useful; reject it so the
    // misconfiguration fails loudly at build time.
    if source_glob.is_some() && matches!(source_extract, Some(Extract::WholeFile)) {
        return Err(cfg(
            "`source.files` (glob-union) cannot use a `whole_file` extract \
             (it would union file contents as set members); use a structured / \
             regex / lines extract"
                .into(),
        ));
    }
    let targets = match opts.targets {
        Some(ts) => Some(resolve_targets(ts, &cfg)?),
        None => None,
    };

    // Pre-validate regex extracts at build time (clean config error,
    // not an error-level eval-time violation).
    validate_extract_regexes(source_extract.as_ref(), targets.as_ref(), &cfg)?;

    validate_shape(
        opts.relation,
        source_extract.as_ref(),
        targets.as_ref(),
        &cfg,
    )?;

    // Reject options the chosen relation ignores, so a misconfiguration
    // fails loudly at build rather than silently doing nothing.
    if opts.skip_header_lines.is_some() && opts.relation != Relation::Identical {
        return Err(cfg(
            "`skip_header_lines` only applies to `relation: identical`".into(),
        ));
    }
    let normalize = opts.normalize.into_list();
    if !normalize.is_empty() && matches!(opts.relation, Relation::Identical | Relation::Resolves) {
        return Err(cfg(format!(
            "`normalize` does not apply to `relation: {:?}` \
             (it compares whole files / paths, not extracted values)",
            opts.relation
        )));
    }
    // `register_as` is meaningful only for `registered` (it templates a member
    // PATH into its list value); reject it elsewhere so a misplaced key fails loud.
    if opts.register_as.is_some() && opts.relation != Relation::Registered {
        return Err(cfg(
            "`register_as` only applies to `relation: registered`".into()
        ));
    }

    let fixer = build_sync_from_fixer(
        spec.fix.as_ref(),
        opts.relation,
        opts.skip_header_lines.unwrap_or(0),
        &source_file,
        source_glob.is_none(),
        source_extract.as_ref(),
        targets.as_ref(),
        &normalize,
        &cfg,
    )?;

    Ok(Box::new(CrossFileRule {
        id: spec.id.clone(),
        level: spec.level,
        policy_url: spec.policy_url.clone(),
        message: spec.message.clone(),
        source_file,
        source_glob,
        source_extract,
        targets,
        relation: opts.relation,
        normalize,
        allow_missing: opts.allow_missing_target,
        skip_header_lines: opts.skip_header_lines.unwrap_or(0),
        register_as: opts.register_as,
        fixer,
    }))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn build_accepts_scalar_and_list_normalize() {
        use crate::test_support::spec_yaml;
        let base = "id: t\nkind: cross_file\nsource:\n  file: a\n  extract:\n    lines: {}\n\
                    targets:\n  files: \"b/*\"\n  extract:\n    lines: {}\nrelation: equals\n";
        // Scalar (the released form) and a list both build.
        assert!(
            build(&spec_yaml(&format!(
                "{base}normalize: semver-minor\nlevel: error\n"
            )))
            .is_ok()
        );
        assert!(
            build(&spec_yaml(&format!(
                "{base}normalize: [trim, semver-minor]\nlevel: error\n"
            )))
            .is_ok()
        );
    }

    #[test]
    fn build_glob_source_requires_a_set_relation() {
        let yaml = "id: t\nkind: cross_file\n\
                    source: { files: \"doc/*.txt\", extract: { regex: 'x(.)' } }\n\
                    targets: [{ file: c, extract: { regex: 'y(.)' } }]\n\
                    relation: equals\nlevel: error\n";
        let err = build(&crate::test_support::spec_yaml(yaml))
            .unwrap_err()
            .to_string();
        assert!(err.contains("set relation"), "{err}");
    }

    #[test]
    fn build_glob_source_rejects_whole_file_extract() {
        // Unioning whole-file CONTENTS as set members is never useful.
        let yaml = "id: t\nkind: cross_file\n\
                    source: { files: \"doc/*.txt\", extract: { whole_file: {} } }\n\
                    targets: [{ file: c, extract: { whole_file: {} } }]\n\
                    relation: set_equals\nlevel: error\n";
        let err = build(&crate::test_support::spec_yaml(yaml))
            .unwrap_err()
            .to_string();
        assert!(err.contains("whole_file"), "{err}");
    }

    #[test]
    fn build_rejects_both_source_file_and_files() {
        let yaml = "id: t\nkind: cross_file\n\
                    source: { file: a, files: \"b/*\", extract: { regex: 'x(.)' } }\n\
                    targets: [{ file: c, extract: { regex: 'y(.)' } }]\n\
                    relation: set_equals\nlevel: error\n";
        let err = build(&crate::test_support::spec_yaml(yaml))
            .unwrap_err()
            .to_string();
        assert!(err.contains("exactly one"), "{err}");
    }

    // ─── identical ──────────────────────────────────────────────

    #[test]
    fn build_rejects_invalid_extract_regex() {
        use crate::test_support::spec_yaml;
        let spec = spec_yaml(
            "id: t\n\
             kind: cross_file\n\
             relation: equals\n\
             source: { file: a.txt, extract: { regex: \"(unclosed\" } }\n\
             targets: { files: \"**/*.txt\", extract: { regex: \".*\" } }\n\
             level: error\n",
        );
        let err = build(&spec).unwrap_err();
        assert!(err.to_string().contains("regex"), "{err}");
    }

    #[test]
    fn build_rejects_skip_header_on_non_identical() {
        use crate::test_support::spec_yaml;
        let spec = spec_yaml(
            "id: t\n\
             kind: cross_file\n\
             relation: equals\n\
             source: { file: a.txt, extract: { regex: \"(.*)\" } }\n\
             targets: { files: \"**/*.txt\", extract: { regex: \"(.*)\" } }\n\
             skip_header_lines: 2\n\
             level: error\n",
        );
        let err = build(&spec).unwrap_err();
        assert!(err.to_string().contains("skip_header_lines"), "{err}");
    }

    #[test]
    fn build_rejects_normalize_on_identical() {
        use crate::test_support::spec_yaml;
        let spec = spec_yaml(
            "id: t\n\
             kind: cross_file\n\
             relation: identical\n\
             source: { file: a.txt }\n\
             targets: { files: \"**/*.txt\" }\n\
             normalize: trim\n\
             level: error\n",
        );
        let err = build(&spec).unwrap_err();
        assert!(err.to_string().contains("normalize"), "{err}");
    }

    #[test]
    fn build_accepts_sync_from_on_identical() {
        use crate::test_support::spec_yaml;
        let spec = spec_yaml(
            "id: t\n\
             kind: cross_file\n\
             relation: identical\n\
             source: { file: canon.txt }\n\
             targets: { files: \"**/copy.txt\" }\n\
             level: error\n\
             fix: { sync_from: {} }\n",
        );
        let rule = build(&spec).expect("sync_from builds on identical");
        assert!(rule.fixer().is_some(), "the sync_from fixer attaches");
    }

    #[test]
    fn build_accepts_sync_from_on_equals_with_structured_targets() {
        // Value propagation: `equals` + a STRUCTURED target extract attaches the
        // CrossFileValueFixer (propagate the source scalar into each target node).
        use crate::test_support::spec_yaml;
        let spec = spec_yaml(
            "id: t\n\
             kind: cross_file\n\
             relation: equals\n\
             source: { file: Cargo.toml, extract: { toml: \"$.workspace.package.version\" } }\n\
             targets: { files: \"crates/*/Cargo.toml\", extract: { toml: \"$.package.version\" } }\n\
             level: error\n\
             fix: { sync_from: {} }\n",
        );
        let rule = build(&spec).expect("sync_from builds on equals + structured targets");
        assert!(rule.fixer().is_some(), "the value fixer attaches");
    }

    #[test]
    fn build_accepts_sync_from_on_equals_with_regex_targets() {
        // Phase 2: a regex-extract target attaches the value fixer (rewrite each
        // capture group 1 to the source value).
        use crate::test_support::spec_yaml;
        let spec = spec_yaml(
            "id: t\n\
             kind: cross_file\n\
             relation: equals\n\
             source: { file: VERSION, extract: { regex: \"^([0-9.]+)$\" } }\n\
             targets: { files: \"**/*.md\", extract: { regex: \"badge-([0-9.]+)-\" } }\n\
             level: error\n\
             fix: { sync_from: {} }\n",
        );
        let rule = build(&spec).expect("sync_from builds on equals + regex targets");
        assert!(rule.fixer().is_some(), "the value fixer attaches");
    }

    #[test]
    fn build_rejects_sync_from_on_equals_with_a_lines_target() {
        // A `lines` (or `whole_file`) target extract has no single scalar to set --
        // rejected at load (only structured / regex targets propagate a value).
        use crate::test_support::spec_yaml;
        let spec = spec_yaml(
            "id: t\n\
             kind: cross_file\n\
             relation: equals\n\
             source: { file: a.txt, extract: { regex: \"(.*)\" } }\n\
             targets: { files: \"**/*.txt\", extract: { lines: {} } }\n\
             level: error\n\
             fix: { sync_from: {} }\n",
        );
        let err = build(&spec).unwrap_err().to_string();
        assert!(
            err.contains("sync_from") && err.contains("no single value"),
            "{err}"
        );
    }

    #[test]
    fn build_accepts_sync_from_on_equals_with_a_mixed_list() {
        // Audit F-4: a LIST of targets mixing a structured + a regex extract builds
        // (both are value extracts).
        use crate::test_support::spec_yaml;
        let spec = spec_yaml(
            "id: t\n\
             kind: cross_file\n\
             relation: equals\n\
             source: { file: VERSION, extract: { regex: \"([0-9.]+)\" } }\n\
             targets:\n\
             \x20 - { file: pkg/Cargo.toml, extract: { toml: \"$.package.version\" } }\n\
             \x20 - { file: README.md, extract: { regex: \"badge-([0-9.]+)-\" } }\n\
             level: error\n\
             fix: { sync_from: {} }\n",
        );
        let rule = build(&spec).expect("a mixed structured+regex list builds");
        assert!(rule.fixer().is_some(), "the value fixer attaches");
    }

    #[test]
    fn build_rejects_sync_from_on_equals_with_a_lines_list_entry() {
        // Audit F-4: a `lines` extract in a LIST entry is rejected (no single value),
        // naming the offending entry.
        use crate::test_support::spec_yaml;
        let spec = spec_yaml(
            "id: t\n\
             kind: cross_file\n\
             relation: equals\n\
             source: { file: VERSION, extract: { regex: \"([0-9.]+)\" } }\n\
             targets:\n\
             \x20 - { file: ok.toml, extract: { toml: \"$.v\" } }\n\
             \x20 - { file: bad.txt, extract: { lines: {} } }\n\
             level: error\n\
             fix: { sync_from: {} }\n",
        );
        let err = build(&spec).unwrap_err().to_string();
        assert!(
            err.contains("no single value") && err.contains("bad.txt"),
            "{err}"
        );
    }

    #[test]
    fn build_rejects_sync_from_on_a_set_relation() {
        // A set relation (subset/superset/set_equals) has no single value to
        // propagate; `sync_from` supports only identical + equals.
        use crate::test_support::spec_yaml;
        let spec = spec_yaml(
            "id: t\n\
             kind: cross_file\n\
             relation: set_equals\n\
             source: { file: a.txt, extract: { regex: \"(\\\\w+)\" } }\n\
             targets: { files: \"**/*.txt\", extract: { regex: \"(\\\\w+)\" } }\n\
             level: error\n\
             fix: { sync_from: {} }\n",
        );
        let err = build(&spec).unwrap_err().to_string();
        assert!(err.contains("sync_from") && err.contains("set"), "{err}");
    }

    #[test]
    fn build_rejects_sync_from_with_skip_header_lines() {
        // A whole-file copy would clobber the header the rule deliberately skips.
        use crate::test_support::spec_yaml;
        let spec = spec_yaml(
            "id: t\n\
             kind: cross_file\n\
             relation: identical\n\
             source: { file: canon.txt }\n\
             targets: { files: \"**/copy.txt\" }\n\
             skip_header_lines: 2\n\
             level: error\n\
             fix: { sync_from: {} }\n",
        );
        let err = build(&spec).unwrap_err().to_string();
        assert!(err.contains("sync_from") && err.contains("header"), "{err}");
    }

    #[test]
    fn build_rejects_an_incompatible_fix_op_on_cross_file() {
        use crate::test_support::spec_yaml;
        let spec = spec_yaml(
            "id: t\n\
             kind: cross_file\n\
             relation: identical\n\
             source: { file: canon.txt }\n\
             targets: { files: \"**/copy.txt\" }\n\
             level: error\n\
             fix: { file_remove: {} }\n",
        );
        let err = build(&spec).unwrap_err().to_string();
        assert!(err.contains("file_remove"), "{err}");
        assert!(err.contains("not compatible with cross_file"), "{err}");
    }

    #[test]
    fn build_surfaces_friendly_untagged_error_through_options_wrapper() {
        // The `expecting` message must reach the user through build()'s
        // `invalid options: {e}` wrapping, not just the isolated enum. Guards a
        // refactor that drops the inner error from the wrapper (audit M3).
        use crate::test_support::spec_yaml;
        let spec = spec_yaml(
            "id: t\n\
             kind: cross_file\n\
             relation: equals\n\
             source: { file: a.txt, extract: { toml: \"$.v\" } }\n\
             normalize: 42\n\
             level: error\n",
        );
        let err = build(&spec).unwrap_err().to_string();
        assert!(
            err.contains("a normalize transform"),
            "friendly text lost through the options wrapper: {err}"
        );
        assert!(!err.contains("NormalizeSpec"), "leaks internal enum: {err}");
    }

    // ─── registered ─────────────────────────────────────────────

    #[test]
    fn build_accepts_registered_with_a_glob_source_and_structured_target() {
        use crate::test_support::spec_yaml;
        let spec = spec_yaml(
            "id: t\n\
             kind: cross_file\n\
             relation: registered\n\
             source: { files: \"crates/*\" }\n\
             register_as: \"{dir}\"\n\
             targets: [{ file: Cargo.toml, extract: { toml: \"$.workspace.members[*]\" } }]\n\
             level: error\n",
        );
        assert!(
            build(&spec).is_ok(),
            "registered + glob source + structured target should build"
        );
    }

    #[test]
    fn build_rejects_registered_with_a_source_extract() {
        // The source is filesystem PATHS, not values extracted from a file.
        use crate::test_support::spec_yaml;
        let spec = spec_yaml(
            "id: t\n\
             kind: cross_file\n\
             relation: registered\n\
             source: { files: \"crates/*\", extract: { toml: \"$.name\" } }\n\
             targets: [{ file: Cargo.toml, extract: { toml: \"$.workspace.members[*]\" } }]\n\
             level: error\n",
        );
        let err = build(&spec).unwrap_err().to_string();
        assert!(
            err.contains("registered") && err.contains("source.extract"),
            "{err}"
        );
    }

    #[test]
    fn build_rejects_registered_without_a_target_extract() {
        use crate::test_support::spec_yaml;
        let spec = spec_yaml(
            "id: t\n\
             kind: cross_file\n\
             relation: registered\n\
             source: { files: \"crates/*\" }\n\
             targets: [{ file: Cargo.toml }]\n\
             level: error\n",
        );
        let err = build(&spec).unwrap_err().to_string();
        assert!(
            err.contains("registered") && err.contains("JSONPath"),
            "{err}"
        );
    }

    #[test]
    fn build_accepts_create_and_register_on_registered() {
        use crate::test_support::spec_yaml;
        let spec = spec_yaml(
            "id: t\n\
             kind: cross_file\n\
             relation: registered\n\
             source: { files: \"crates/*\" }\n\
             targets: [{ file: Cargo.toml, extract: { toml: \"$.workspace.members[*]\" } }]\n\
             level: error\n\
             fix: { create_and_register: {} }\n",
        );
        let rule = build(&spec).expect("create_and_register builds on registered");
        assert!(rule.fixer().is_some(), "the register fixer attaches");
    }

    #[test]
    fn build_rejects_create_and_register_on_a_non_registered_relation() {
        use crate::test_support::spec_yaml;
        let spec = spec_yaml(
            "id: t\n\
             kind: cross_file\n\
             relation: identical\n\
             source: { file: canon.txt }\n\
             targets: { files: \"**/copy.txt\" }\n\
             level: error\n\
             fix: { create_and_register: {} }\n",
        );
        let err = build(&spec).unwrap_err().to_string();
        assert!(
            err.contains("create_and_register") && err.contains("registered"),
            "{err}"
        );
    }

    #[test]
    fn build_rejects_create_and_register_target_without_a_star_suffix() {
        // The target extract must select array ELEMENTS with a trailing `[*]`, so
        // the check sees each element and the fix can locate the array.
        use crate::test_support::spec_yaml;
        let spec = spec_yaml(
            "id: t\n\
             kind: cross_file\n\
             relation: registered\n\
             source: { files: \"crates/*\" }\n\
             targets: [{ file: Cargo.toml, extract: { toml: \"$.workspace.members\" } }]\n\
             level: error\n\
             fix: { create_and_register: {} }\n",
        );
        let err = build(&spec).unwrap_err().to_string();
        assert!(err.contains("[*]"), "{err}");
    }

    #[test]
    fn build_rejects_register_as_on_a_non_registered_relation() {
        use crate::test_support::spec_yaml;
        let spec = spec_yaml(
            "id: t\n\
             kind: cross_file\n\
             relation: equals\n\
             source: { file: a.txt, extract: { regex: \"(.*)\" } }\n\
             targets: { files: \"**/*.txt\", extract: { regex: \"(.*)\" } }\n\
             register_as: \"{path}\"\n\
             level: error\n",
        );
        let err = build(&spec).unwrap_err().to_string();
        assert!(err.contains("register_as"), "{err}");
    }

    // ─── build-time shape validation ────────────────────────────

    #[test]
    fn build_enforces_per_relation_shape() {
        use crate::test_support::spec_yaml;
        // identical with a stray source.extract -> rejected.
        let bad_identical = "id: t\nkind: cross_file\nsource:\n  file: a\n  \
            extract:\n    lines: {}\ntargets:\n  files: \"b/*\"\nrelation: identical\nlevel: error\n";
        assert!(
            build(&spec_yaml(bad_identical)).is_err(),
            "identical must not take source.extract"
        );
        // resolves with targets -> rejected.
        let bad_resolves = "id: t\nkind: cross_file\nsource:\n  file: a\n  \
            extract:\n    lines: {}\ntargets:\n  files: \"b/*\"\n  extract:\n    lines: {}\n\
            relation: resolves\nlevel: error\n";
        assert!(
            build(&spec_yaml(bad_resolves)).is_err(),
            "resolves must not take targets"
        );
        // value relation missing source.extract -> rejected.
        let bad_value = "id: t\nkind: cross_file\nsource:\n  file: a\ntargets:\n  \
            files: \"b/*\"\n  extract:\n    lines: {}\nrelation: subset\nlevel: error\n";
        assert!(
            build(&spec_yaml(bad_value)).is_err(),
            "value relation needs source.extract"
        );
        // valid identical (no extract anywhere) -> builds.
        let ok_identical = "id: t\nkind: cross_file\nsource:\n  file: README.md\n\
            targets:\n  files: \"crates/*/README.md\"\nrelation: identical\nlevel: error\n";
        assert!(
            build(&spec_yaml(ok_identical)).is_ok(),
            "valid identical should build"
        );
        // valid resolves (source extract, no targets) -> builds.
        let ok_resolves = "id: t\nkind: cross_file\nsource:\n  file: Cargo.toml\n  \
            extract:\n    toml: \"$.workspace.members[*]\"\nrelation: resolves\nlevel: error\n";
        assert!(
            build(&spec_yaml(ok_resolves)).is_ok(),
            "valid resolves should build"
        );
    }
}
